### ISSUE TITLE
Why do flake8-isort have different license then isort or flake8?

### ISSUE THREAD

**Issue by Vladislav-Bartalevich** [gforcada/flake8-isort#137]
flake8-isort license is GPL v2 but isort and flake8 use MIT.
Is there any purpose in using difference licenses for flake8-isort plugin?

**Comment by gforcada** [comment]
Hey sorry, I'm very much busy as of late 😵‍💫 

Why? Basically because I did not check for what was used elsewhere, and as a firm FOSS believer, the no brain decision was to make it GPL v2. I did not spend too much time thinking on it to be honest 😅 

In practical terms is that a problem? 🤔

**Comment by Vladislav-Bartalevich** [comment]
Well, to be completely honest, it's an issue for commercial software :)

When developing something commercial, you're usually not able to make the source code public. But if you're using flake8-isort, because of the GPL license, you must.

It's possible to live without it (just use isort instead), so I was just curious if it was done by purpose or not :)

**Comment by Vladislav-Bartalevich** [comment]
GPL is a very strict kind of license, you know :)

That's why some huge projects like psycopg decided to use LGPL or MPL instead

**Comment by gforcada** [comment]
Yes, and plenty of other projects use other licenses as well 😅 

That's why I was asking, in practical terms, why is your concern? A re-licensing of this flake8 extension could be done, sure, why do we want it, just for the matter of making it less strict? Who is going to benefit from it?

**Comment by Vladislav-Bartalevich** [comment]
Commercial software developers, of course. As I said previously, you must make your code public if you decide to use flake8-isort because of the GPL. But usually commercial code is private.

Of course, the open source community wouldn't benefit from it.

And anyway, as I said before, it's possible to overcome this issue if you replace the flake8-isort with isort :)
