### ISSUE TITLE
Support Python3.12

### ISSUE THREAD

**Issue by neugepower** [gforcada/flake8-isort#139]
By default `pkg_resources` seems to be [not available anymore](https://docs.python.org/3.12/whatsnew/3.12.html) in Python3.12. The package is used in [flake_isort.py](https://github.com/gforcada/flake8-isort/blob/75e37f8002c8fc741e7a20c58df79b7a3d9a11f2/flake8_isort.py#L8). It would be great to have `flake8-isort` Python3.12 ready. Any chance this package could be fixed to support Python3.12 out-of-the-box. That would be fantastic, thanks!

**Comment by gforcada** [comment]
Hey, sorry for the delay and thanks for opening the issue! 💯 

Indeed, seems that we have a problem with `pkg_resources` being removed. Given the usage, which is only to get the version of the package itself, we might as well hardcode it and bump it manually.

Meanwhile though, given that other problems might be not that obvious, a PR adding a GHA targeting 3.12 would be great, I might have a look at it right away 🚀

**Comment by gforcada** [comment]
Support added, I will make a release 😄

**Comment by neugepower** [comment]
Awesome, thank you! We will give it a try as soon as everything got propagated.

**Comment by gforcada** [comment]
`6.1.0` was released 🎉
