### ISSUE TITLE
Document relation to flake8-import-order

### ISSUE THREAD

**Issue by Tarrasch** [gforcada/flake8-isort#25]
I've found there exists another package, [flake8-import-order](https://pypi.python.org/pypi/flake8-import-order). It would be good if this library could contrast the two libraries. So we first-time-users can know which software best applies to us. Thanks! :candy:

**Comment by gforcada** [comment]
@Tarrasch good point. From what I just read about flake8-import-order it seems that they bundle the logic on how the imports should be sorted, and you have a few options to choose. On the other hand flake8-isort defers all the logic to [isort](https://pypi.python.org/pypi/isort) and with it you can do any sort of imports sorting.

IMHO isort is far more powerful than flake8-import-order when it comes to import sorting needs. If one of the styles from flake8-import-order fits you, then you can as well use that.

Would you mind creating a pull request explaining the differences I pointed here? Or with that do you think is enough and I can copy and adapt myself?
