### ISSUE TITLE
Can't find isort config?

### ISSUE THREAD

**Issue by thornycrackers** [gforcada/flake8-isort#27]
Inside of my docker container when I run flake8 I get this error:

    test.py:0:1: I002 no configuration found (.isort.cfg or [isort] on setup.cfg)

But I have an isort config in my home directory:

    bash-4.3# cat ~/.isort.cfg
    [settings]
    not_skip=__init__.py
    indent='    '
    multi_line_output=5
    known_django=django
    sections=FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
    skip=migrations
    include_trailing_comma=True

It says that isort configs can be in the home directory but flake8 isn't picking it up? Does it look and environment variables or something to find the home directory?

**Comment by gforcada** [comment]
Hi @thornycrackers thanks for the report!

The code that looks for a config file is this one: https://github.com/gforcada/flake8-isort/blob/master/flake8_isort.py#L73-L101

Could it be, just wild guessing, that your project is *outside* your home folder? The current code just traverses the folder structure from the project folder all the way up to the filesystem root, if the project happens to not be inside your homefolder, i.e. ``/my-projects/XXX`` then it will not find it.

If that's the case the logic could be expanded to do a last check on the user homefolder as well.

**Comment by thornycrackers** [comment]
You nailed it haha it's in a separated directory. Yeah I think it would be good to add that check just to check there last 👍

**Comment by gforcada** [comment]
@thornycrackers I made a new release (2.2) with a fix for it, would you mind trying it out?

**Comment by thornycrackers** [comment]
I think your solution will work but you have to make a few more tweaks yet. I think that it's an issue with the init method setting search_current to True.

```
def __init__(self, tree, filename, search_current=True):
    self.filename = filename
    self.search_current = search_current
```
Because of this you will never actually get to your code because it will always return `self.search_isort_config_at_current()`
```
if self.search_current:
    return self.search_isort_config_at_current()

# last attempt, check home folder
home = expanduser('~')
if self._search_config_on_path(home):
    return True
```
I tested this out and the code never got to the expanduser section.
