### ISSUE TITLE
Using setup.cfg not .isort.cfg

### ISSUE THREAD

**Issue by plumdog** [gforcada/flake8-isort#3]
isort allows using an `[isort]` section in `setup.cfg` rather than using a separate `.isort.cfg` file. (https://pypi.python.org/pypi/isort says "Or, if you prefer, you can add an isort section to your project’s setup.cfg with any desired settings.")

The benefit of doing this is that then the configuration is passed to the [git hook](https://bitbucket.org/tarek/flake8/src/a209fb69350c572c9b2d7b4b09c7657be153be5e/flake8/hooks.py?at=default&fileviewer=file-view-default#hooks.py-18), but it isn't if the configuration is just in `.isort.cfg`.

The git hook presents another problem as flake8 doesn't allow the passing of options to it, so we can't pass the option to not check for it.

One solution to this would be to check for the file and the section in `setup.cfg` and only error if neither were found - ie, to extend `search_isort_config`. This would have the extra benefit that if you weren't using `.isort.cfg`, you wouldn't have to pass the option every time you ran `flake8`.

I'll see if I can get a pull-request together, but please let me know if there's something I've missed.

**Comment by gforcada** [comment]
@plumdog that looks really good, I will try to review and release the pull request as it comes. Thanks in advance!

**Comment by do3cc** [comment]
https://github.com/django/django/blob/master/setup.cfg

**Comment by Jc2k** [comment]
I've just added `isort` to my project and hit the same thing. It would be really good if `flake8-isort` could read from `setup.cfg` like `isort` does!

**Comment by do3cc** [comment]
This is an easy task, I can help you if you get stuck on implementation.

**Comment by gforcada** [comment]
Pull request merged and released (1.1)!
