### ISSUE TITLE
isort >=4.2.8 now supports tox.ini configuration

### ISSUE THREAD

**Issue by cas--** [gforcada/flake8-isort#34]
This feature should be added add to the plugin. I'll look into creating a PR at some point, unless someone else gets around to it sooner :stuck_out_tongue_closed_eyes: 

https://github.com/timothycrosley/isort/issues/487

**Comment by gforcada** [comment]
@cas-- hi! thanks for reporting it. You mean that flake8-isort should also look at ``tox.ini`` files for ``[isort]`` configuration?

**Comment by cas--** [comment]
Yes

**Comment by cas--** [comment]
Actually looking at settings source code, perhaps also look for `.editorconfig`

https://github.com/timothycrosley/isort/blob/master/isort/settings.py#L137

**Comment by jleclanche** [comment]
@cas-- are you working on a PR for this? It's be really great!
