### ISSUE TITLE
flake8-isort version in code is not being updated

### ISSUE THREAD

**Issue by cas--** [gforcada/flake8-isort#36]
The current release of flake8-isort is `2.2.1` in setup.py but  `2.1.3` is in code

**Comment by gforcada** [comment]
@cas-- thanks for noticing, I always forget about this. I will try to be more strict to myself when making releases!

**Comment by gforcada** [comment]
Fixed for next version.

**Comment by florisla** [comment]
@gforcada Might I suggest to use [bump2version](https://pypi.org/project/bump2version/) and integrate that in your release procedure.

**Comment by gforcada** [comment]
@florisla thanks, I will try to remember it!
