### ISSUE TITLE
isort errors inside of tox. 

### ISSUE THREAD

**Issue by jrbenny35** [gforcada/flake8-isort#37]
Hello, I am getting these errors running isort 2.2.1, python 3.6.0, and tox 2.7.0. I am running it within tox as well as with the default config.

The first error indicates the first 2 lines are in the wrong position or I001:
```
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By

from foxpuppet import expected
from foxpuppet.windows import BaseWindow
from foxpuppet.windows.browser.navbar import NavBar
from foxpuppet.windows.browser.notifications import BaseNotification
```
And it also says that there is an ```I004 isort found an unexpected blank line in imports``` for the blank line inbetween on line 3. However running isort directly on the file shows no errors. Any tips?

**Comment by jrbenny35** [comment]
Looks like I need to install the local package I wanted to test against! Closing,

**Comment by gforcada** [comment]
@jrbenny35 thanks for using flake8-isort and taking the time to report issues with it!

I'm glad you found the solution! By *install the local package* you mean the package you are linting? So a ``pip install -e .`` or making it available on tox?

I have not much experience with tox and flake8, but as the flake8 API provides the entry points I've never looked much into how the configuration and scan of the files goes.

**Comment by jrbenny35** [comment]
It would be this: http://tox.readthedocs.io/en/latest/config.html#confval-skip_install=BOOL
