### ISSUE TITLE
Add styles

### ISSUE THREAD

**Issue by gforcada** [gforcada/flake8-isort#5]
To make flake8-isort more helpful and less bothersome to configure it could have a notion of styles:

A style is a predefined set of isort options that will be used when a configuration option/command-line switch (just like the current ``--no-isort-config``) is used.

i.e. ``flake8 --isort-style plone``

**Comment by jayvdb** [comment]
It would be a great feature for `isort` .  However I do not think it is very helpful for this flake8 plugin to override the settings that `isort` loads from its configuration.

**Comment by gforcada** [comment]
@jayvdb actually isort itself wants to provide styles on its own, so this flake8 plugin does not need to provide them at all and rely on what's configured on isort itself.
