### ISSUE TITLE
Use command line params of flake8

### ISSUE THREAD

**Issue by Xenya0815** [gforcada/flake8-isort#51]
I execute flake8 with the command line param `--max-line-length=120`. It would be cool if that param is also passed to isort.

The other interesting flake8 cli param is `--config`. My team has linting configurations for all projects. With flake8 I can reference to that files by using the `--config` param. You support already a `setup.cfg` so it would be nice to use the same as the one, used by flake8.

**Comment by gforcada** [comment]
@Xenya0815 hi!

Thanks for taking the time to report issues/enhancements for flake8-isort, and to actually use it! :+1: 

Would you have time to provide a pull request, or do some research on which API calls one needs to do to flake8 to get that data? either of that would help a lot on creating a patch to fix it and getting it released :smiley:

**Comment by gforcada** [comment]
Please re-open if you feel like it 👍🏾
