### ISSUE TITLE
Installation instructions is unclear

### ISSUE THREAD

**Issue by ogonkov** [gforcada/flake8-isort#52]
It's unclear that installation requires `select` to have `I`, to actually output `isort` linting result

**Comment by gforcada** [comment]
Hi @ogonkov thanks for using flake8-isort and taking the extra time to actually report the issues you found with it.

I'm sorry, but I don't understand what yiu mean.  flake8-isort does not need a package named select nor a package named I. How did you install flake8-isort?

**Comment by ogonkov** [comment]
Sorry, i was unclear aswell :)

For our installation of `flake8` we have `setup.cfg`, that looks like:

```cfg
[flake8]
select = E,W,F
```

To make `flake8-isort` to work, we should add `I` here, without it, running lint just didn't have any effect.
