### ISSUE TITLE
Reason for GPL 2.0?

### ISSUE THREAD

**Issue by sliverc** [gforcada/flake8-isort#56]
Is there any special reason that GPL version 2.0 has been chosen for flake8-isort?

[isort](https://github.com/timothycrosley/isort/blob/develop/LICENSE) and [flake8](https://github.com/PyCQA/flake8/blob/master/LICENSE) are both released under MIT. Using flake8-isort some users might have licensing issues.

**Comment by gforcada** [comment]
No, there was no special reason, the setup.py that I copied over probably had that very same license, I guess most of the flake8 plugins I created have such license.

IANAL but if we want to relicense we will have to ask all contributors (16 according to github).

I would be ok with a relicense to MIT/LGPL or similar, but I'm just too busy to have that as a priority. I would welcome and support anyone doing it though.

**Comment by sliverc** [comment]
Thanks for your quick feedback.

I am thinking of using flake8-isort in [django-rest-framework-json-api](https://github.com/django-json-api/django-rest-framework-json-api) but because of GPL it would cause issue with BSD license and technically I would have to relicense it under GPL.

So I would be really interested in changing this. Others might have looked at LICENSE as well and decided not to use flake8-isort for this reason.

Hence let me try to create a PR changing LICENSE and ask for reviews of all contributors to give their consensus. Let's see whether we get all together or if not I guess their code changes would need to be analyzed.

**Comment by gforcada** [comment]
Again, IANAL but if you are not distributing flake8-isort, the license does not matter, isn't it? :thinking:

**Comment by sliverc** [comment]
I thought the same thing just after writing my comment above that technically using flake8-isort is not really linking it into the code so it would be OK even when it is licensed under GPL.

Question is though whether everyone thinks this way and when seeing `LICENSE` being GPL might simply not look at `flake8-isort` at all out of caution. Maybe changing LICENSE might increase adoption therefore.

This said I am open to create a PR to change LICENSE but if you think it is too much trouble we can also close this ticket. Let me know.

**Comment by gforcada** [comment]
I'm not sure if there are much potential users of flake8-isort that looked elsewhere upon seeing the license... given that is a specific plugin for a quality assurance tool only meant for a particular programming language, I don't see much people interested in it **and** that on top of that are really concerned about licensing issues...

Prove me wrong though. If you don't mind, I will close the issue.

**Comment by tony** [comment]
@gforcada I have to agree with this, I think it's probably best to remove the GPL license completely, unless you know what / why you're using it.

If it's BSD/MIT licensed, no point in adding a GPL - as BSD/MIT is forward compatible to it. 

> Question is though whether everyone thinks this way and when seeing LICENSE being GPL might simply not look at flake8-isort at all out of caution. Maybe changing LICENSE might increase adoption therefore.

Agreed on that.

> IANAL but if we want to relicense we will have to ask all contributors (16 according to github).

I think it'd be good to have future commits licensed MIT or BSD.

You could also fork and rebase-away smaller commits sandwiched in between. That way the code after isn't a derivative and you don't have to rewrite a whole project from scratch.

**Comment by kavdev** [comment]
@gforcada any chance you'll reconsider moving to an MIT license?
