### ISSUE TITLE
flake-isort generating false warnings when running flake8 on Windows

### ISSUE THREAD

**Issue by AlexArcPy** [gforcada/flake8-isort#65]
# Bug report

`flake-isort` is generating false warnings when running `flake8` with `flake8-isort` installed on Windows 10 machine.

## What's wrong

Having file with the contents:

```python
# -*- coding: UTF-8 -*-
"""Module docstring."""

print('hello')
```

Running

```bash
C:\Temp\SampleEnvIsortOnly\Scripts
(SampleEnvIsortOnly) λ flake8 "C:\Development\Flake8PluginDev\foo.py"
```

on Windows 10 gives

```
C:\Development\Flake8PluginDev\foo.py:2:1: I001 isort found an import in the wrong position
C:\Development\Flake8PluginDev\foo.py:4:1: I003 isort expected 1 blank line in imports, found 0
```

when there are really no imports in the file.

Running 

```bash
(SamplePyEnv) linuxuser@LinuxMachine:~/Development/SamplePyEnv$ flake8 /home/linuxuser/Development/Sample/foo.py
```

on the file with the same contents on Linux Ubuntu does not produce any warnings.

## How is that should be

The `flake8-isort` should not generate these false warnings for file with the provided content on Windows machines.

### flake8 information

Contents of `flake8 --bug-report`:

```
(SampleEnvIsortOnly) λ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "39.0.1"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.6",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8_isort",
      "version": "2.3"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.3.1"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "1.6.0"
    }
  ],
  "version": "3.5.0"
}
```

### pip information

Contents of `pip freeze`:

```
(SampleEnvIsortOnly) λ pip freeze
flake8==3.5.0
flake8-isort==2.5
isort==4.3.4
mccabe==0.6.1
pycodestyle==2.3.1
pyflakes==1.6.0
testfixtures==6.3.0
```

**Comment by AlexArcPy** [comment]
@sobolevn , I think you may be interested in this if you care for Windows users running the wemake-python-styleguide linter :)

**Comment by gforcada** [comment]
@AlexArcPy hi!

First of all let me apologize for replying so late. :bowing_man: 

I'm afraid I don't have a windows machine to test it, what's the output of ``isort``? Does it fail as well there? :thinking:

**Comment by AlexArcPy** [comment]
@gforcada thanks for getting back, no worries at all! It seems as the problem is specific to my machine as on another Windows machine it works well. I'd just ignore this issue!
