### ISSUE TITLE
TBD: Add support for pyproject.toml

### ISSUE THREAD

**Issue by KyleKing** [gforcada/flake8-isort#66]
isort _will_ eventually support a `[tool.isort]` section in pyproject.toml: https://github.com/timothycrosley/isort#configuring-isort / https://github.com/timothycrosley/isort/pull/798

Not sure what the release plan for isort is. The develop branch is 300 commits ahead the last isort release ([4.3.4 in Feb 2018](https://github.com/timothycrosley/isort/releases)). Once isort is updated, I can help submit a PR to flake8-isort

I think there would need to be a new section for `[tool.isort]` and pyproject.toml here: https://github.com/gforcada/flake8-isort/blob/master/flake8_isort.py#L135-L141, some related updates to the test, and some other minor changes

**Comment by gforcada** [comment]
I would rather have https://github.com/timothycrosley/isort/issues/574 done :-) which would solve all the complexity we have here

**Comment by KyleKing** [comment]
Oh that would make everything easier!
