### ISSUE TITLE
Add test for python3.8

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-isort#81]
Currently both `tox.ini` and `travis.yml` do not support the latest python version: `3.8`.

I can send a PR with the fix! 

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by gforcada** [comment]
@sobolevn yes please, go ahead :) (sorry for the delays, being a father of two kids and the coronavirus around takes a lot of time :sweat_smile: )
