### ISSUE TITLE
Incomplete pyproject.toml support

### ISSUE THREAD

**Issue by cloos** [gforcada/flake8-isort#83]
While 53bc3028 added isort with pyproject.toml support as a dependency,
it was missed to update the `_search_config_on_path` method to also
look for a `tool.isort` section in `pyproject.toml`:
https://github.com/gforcada/flake8-isort/blob/27eb1c120f6f4a71cf90d6e7918b2200b8318fe8/flake8_isort.py#L128-L151

If you currently have `tool.isort` section in `pyproject.toml`, you always get the following error:
I002 no configuration found (.isort.cfg or [isort] in configs)

**Comment by jnns** [comment]
Thanks for mentioning this. There's already a [pull request](https://github.com/gforcada/flake8-isort/pull/79) to improve support for `pyproject.toml` and that will resolve this issue.

**Comment by caiolopes** [comment]
Can we close this since https://github.com/gforcada/flake8-isort/pull/79 is merged?

**Comment by gforcada** [comment]
@caiolopes yes, thanks for taking the time to review what can be closed already :100:
