### ISSUE TITLE
Can't change line length

### ISSUE THREAD

**Issue by Dreamsorcerer** [gforcada/flake8-isort#87]
I keep getting a violation telling me that an import is in the wrong order, but it only appears if the line is over 79 characters.

In `.flake8` I added:
```
[isort]
combine_start = True
line_length = 999
use_parentheses = True
```

That has removed any errors about not being able to find the config, but clearly it is not updating the line length.

**Comment by gforcada** [comment]
@Dreamsorcerer hi! thanks for reporting your usage with flake8-isort, I'm sorry to hear that you are having problems with it though :confused: 

Would you mind trying to create a minimal reproducible example? i.e. which isort/flake8/flake8-isort versions are you using, an example python text file and the `.flake8` configuration you just mentioned? This way I could try to reproduce it locally.

One question though, does `isort` itself say anything if you run it on the source file? :thinking:

**Comment by Dreamsorcerer** [comment]
It's reproducible by just making an import over the line length, e.g. just this in a file:
```
from apple import another, apple, banana, carrot, daikon, eggy_stuff, forty, something_else
```

This on it's own produces the error:
`test.py:1:1: I001 isort found an import in the wrong position`
Which is completely useless, and took me 20 minutes the first time to figure out it was the line length. But, changing the flake8 config as per the bug description does not change the line length isort uses.

isort wants to change it to:
```
from apple import (another, apple, banana, carrot, daikon, eggplant, forty,
                   something_else)
```
But, I assume that isort will not be looking at the .flake8 config when run directly, so this is expected behaviour.
