### ISSUE TITLE
Unresolvable isort version

### ISSUE THREAD

**Issue by cimourdain** [gforcada/flake8-isort#93]
The current version restrict isort version as `'isort[pyproject] >= 4.3.5, <5',`.

In pypi, no isort version match this requirement, the lastest 4.x version is 4.3.21 : https://pypi.org/project/isort/#history

**Comment by bnavigator** [comment]
why would that not be resolvable?

**Comment by cimourdain** [comment]
my bad, i misinterpreted my unresolved dependencies issue.
